create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  product_id text not null,
  user_email text not null,
  username text,
  rating integer not null check (rating between 1 and 5),
  comment text not null,
  created_at timestamptz not null default now(),
  constraint reviews_product_user_unique unique (product_id, user_email)
);

alter table public.reviews enable row level security;

drop policy if exists "Reviews are readable by everyone" on public.reviews;
create policy "Reviews are readable by everyone"
  on public.reviews
  for select
  using (true);

drop policy if exists "Customers can submit reviews" on public.reviews;
create policy "Customers can submit reviews"
  on public.reviews
  for insert
  with check (true);
