-- Run this once in Supabase Dashboard > SQL Editor.
-- Cart and wishlist rows are stored per website user email.

create table if not exists public.cart_items (
  id bigint generated by default as identity primary key,
  user_email text not null,
  product_id text not null,
  product_data jsonb not null default '{}'::jsonb,
  quantity integer not null default 1 check (quantity > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint cart_items_user_product_unique unique (user_email, product_id)
);

create table if not exists public.wishlist_items (
  id bigint generated by default as identity primary key,
  user_email text not null,
  product_id text not null,
  product_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint wishlist_items_user_product_unique unique (user_email, product_id)
);

create index if not exists cart_items_user_email_idx
  on public.cart_items (user_email);

create index if not exists wishlist_items_user_email_idx
  on public.wishlist_items (user_email);

alter table public.cart_items enable row level security;
alter table public.wishlist_items enable row level security;

drop policy if exists "Cart items are readable" on public.cart_items;
create policy "Cart items are readable"
  on public.cart_items for select
  using (true);

drop policy if exists "Cart items can be inserted" on public.cart_items;
create policy "Cart items can be inserted"
  on public.cart_items for insert
  with check (true);

drop policy if exists "Cart items can be updated" on public.cart_items;
create policy "Cart items can be updated"
  on public.cart_items for update
  using (true)
  with check (true);

drop policy if exists "Cart items can be deleted" on public.cart_items;
create policy "Cart items can be deleted"
  on public.cart_items for delete
  using (true);

drop policy if exists "Wishlist items are readable" on public.wishlist_items;
create policy "Wishlist items are readable"
  on public.wishlist_items for select
  using (true);

drop policy if exists "Wishlist items can be inserted" on public.wishlist_items;
create policy "Wishlist items can be inserted"
  on public.wishlist_items for insert
  with check (true);

drop policy if exists "Wishlist items can be updated" on public.wishlist_items;
create policy "Wishlist items can be updated"
  on public.wishlist_items for update
  using (true)
  with check (true);

drop policy if exists "Wishlist items can be deleted" on public.wishlist_items;
create policy "Wishlist items can be deleted"
  on public.wishlist_items for delete
  using (true);

grant select, insert, update, delete on public.cart_items to anon, authenticated;
grant select, insert, update, delete on public.wishlist_items to anon, authenticated;
grant usage, select on sequence public.cart_items_id_seq to anon, authenticated;
grant usage, select on sequence public.wishlist_items_id_seq to anon, authenticated;
